spring:
  cloud:
    openservicebroker:
      catalog:
        services:
          - id: 3101b971-1044-4816-a7ac-9ded2e028079
            name: sample
            description: A sample service
            bindable: true
            tags:
              - sample
            plans:
              - id: 2451fa22-df16-4c10-ba6e-1f682d3dcdc9
                bindable: true
                name: standard
                description: A sample plan
                free: true

    appbroker:
      services:
        - service-name: sample
          plan-name: standard
          apps:
            - name: sample-service-app1
              path: classpath:sample-app-service.jar

      deployer:
        cloudfoundry:
          api-host: https://api.run.haas-222.pez.pivotal.io
          api-port: 443
          username: admin
          password: fRgzFcrIyMQm9eTlrIBF8Vkk9hW0Qg_h
          default-org: mushtaq
          default-space: apps
